dependencies: flask_cors
  boto3
  python-time

GOOGLE_OAUTH_ENV:
  CLIENT_ID: "195044032993-1eohkc391ob5ltbtflj69rfse2960sn5.apps.googleusercontent.com"
  CLIENT_SECRET: "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"
